### ISSUE TITLE
Support for higher resolutions

### ISSUE THREAD

**Issue by akien-mga** [cxong/FallingTime#12]
I know that the game is optimised for low resolution screens, but since it also builds and runs fine on desktop computers with hires screens, it would be nice to have an option to scale the main window.

On my 1920x1080 monitor, the 320x240 window is... small :)

Maybe you could add support for:
- scaling height and width by a power of two, thus preserving aspect ratio
- stretching the whole window to an arbitrary resolution and/or fullscreen

**Comment by cxong** [comment]
The game is written under SDL 1.2 which doesn't natively support scaling.

There are two ways to go about this then:
- Actually use a bigger window, e.g. 640x480, but upscale all sprites. The game code uses resolution-independent units so this is easy. The gameplay will look smoother but limited to integer multiples of 320x240.
- Upscale everything properly. I might use this as an excuse to port to SDL 2. Everything will look blurry though because it's all upscaled
